# This is a basic workflow to help you get started with Actions

name: automation-practice

# Controls when the workflow will run
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: app-version-one
      - name: Start server in the background
        run: npm start &
        working-directory: app-version-one
      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v1
        with:
          working-directory: test-framework
          browser: chrome
          headed: true
