name: E2E
on: push
jobs:
  test-app-one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install root dependencies
        uses: bahmutov/npm-install@v1

      - name: install app
        run: npm install
        working-directory: app-version-one
      - name: Start server in the background
        run: npm run start

      # Cypress has its own package.json in folder "e2e"
      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v1
        with:
          working-directory: e2e
