name: E2E
on: push
jobs:
  test-app-one:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      - name: install app
        run: |
          npm install
          Get-ChildItem
        working-directory: app-version-two

      - name: back to app
        run: |
          cd..
          Get-ChildItem

      - name: Install root dependencies
        uses: bahmutov/npm-install@v1

      - name: Start server in the background
        run: |
          Get-ChildItem
          npm start &

      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: test-framework
          browser: chrome
